---

# UFW

- name: ufw_allow
  ufw:
    rule:      allow
    port:      "{{ item.port }}"
    proto:     "{{ item.proto }}"
    direction: "{{ item.direction }}"
  with_items:
    # Inbound
    - { port: '80',    proto: 'tcp', direction: 'in'}    # Mesos UI
    - { port: '8080',  proto: 'tcp', direction: 'in'}    # Marathon UI
    - { port: '4400',  proto: 'tcp', direction: 'in'}    # Chronos UI
    - { port: '52222', proto: 'tcp', direction: 'in'}
    - { port: '52931', proto: 'tcp', direction: 'in'}
    - { port: '2181',  proto: 'tcp', direction: 'in'}
    - { port: '2888',  proto: 'tcp', direction: 'in'}
    - { port: '3888',  proto: 'tcp', direction: 'in'}
    # Outbound
    - { port: '52222', proto: 'tcp', direction: 'out'}
    - { port: '52931', proto: 'tcp', direction: 'out'}
    - { port: '2181',  proto: 'tcp', direction: 'out'}
    - { port: '2888',  proto: 'tcp', direction: 'out'}
    - { port: '3888',  proto: 'tcp', direction: 'out'}

# Packages

- name: install_packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - "mesosphere"
  register: install_packages

# Configure Zookeeper

- name: amend_zk_myid
  when: install_packages|success
  copy:
    content: "{{ mesos_master_id }}"
    dest:    /etc/zookeeper/conf/myid
    owner:   root
    group:   root
    mode:    "u=rw,g=r,o=r"
  notify:
    - restart_zookeeper

- name: amend_zk_zoo_cfg
  when: install_packages|success
  template:
    src:   zoo.cfg.j2
    dest:  /etc/zookeeper/conf/zoo.cfg
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"
  notify:
    - restart_zookeeper

# Configure Mesos

- name: amend_mesos_zk
  when: install_packages|success
  template:
    src:   mesos_zk.j2
    dest:  /etc/mesos/zk
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"
  notify:
    - restart_mesos_master

- name: amend_mesos_master_quorum
  when: install_packages|success
  copy:
    content: "{{ mesos_quorum }}"
    dest:    /etc/mesos-master/quorum
    owner:   root
    group:   root
    mode:    "u=rw,g=r,o=r"
  notify:
    - restart_mesos_master

- name: amend_mesos_master_ip
  when: install_packages|success
  copy:
    content: "{{ ansible_default_ipv4.address }}"
    dest:    /etc/mesos-master/ip
    owner:   root
    group:   root
    mode:    "u=rw,g=r,o=r"
  notify:
    - restart_mesos_master

- name: amend_mesos_master_hostname
  when: install_packages|success
  copy:
    content: "{{ ansible_fqdn }}"
    dest:    /etc/mesos-master/hostname
    owner:   root
    group:   root
    mode:    "u=rw,g=r,o=r"
  notify:
    - restart_mesos_master

- name: amend_default_mesos_master
  when: install_packages|success
  template:
    src:   mesos-master.j2
    dest:  /etc/default/mesos-master
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"
  notify:
    - restart_mesos_master

# Configure Marathon

- name: create_marathon_conf_dir
  when: install_packages|success
  file:
    path:  /etc/marathon/conf
    state: directory
    owner: root
    group: root
    mode:  "u=rwx,g=r,o=r"
  register: create_marathon_conf_dir

- name: amend_marathon_hostname
  when: install_packages|success and create_marathon_conf_dir|success
  copy:
    content: "{{ ansible_fqdn }}"
    dest:  /etc/marathon/conf/hostname
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"
  notify:
    - restart_marathon

- name: amend_marathon_master
  when: install_packages|success and create_marathon_conf_dir|success
  template:
    src:   marathon_master.j2
    dest:  /etc/marathon/conf/master
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"
  notify:
    - restart_marathon

- name: amend_marathon_zk
  when: install_packages|success and create_marathon_conf_dir|success
  template:
    src:   marathon_zk.j2
    dest:  /etc/marathon/conf/zk
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"
  notify:
    - restart_marathon

- name: amend_default_marathon
  when: install_packages|success
  template:
    src:   default_marathon.j2
    dest:  /etc/default/marathon
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"
  notify:
    - restart_marathon

# Configure init scripts

- name: amend_init_mesos_slave_override
  when: install_packages|success
  copy:
    content: "manual"
    dest:    /etc/init/mesos-slave.override
    owner:   root
    group:   root
    mode:    "u=rw,g=r,o=r"
  notify:
    - stop_mesos_slave
    - restart_zookeeper
    - restart_mesos_master
    - restart_chronos
    - restart_marathon
